<#
One-shot script: appends the new feature-004 localization keys to all 9
shipped language JSON files (log.event.*, settings.language.*,
settings.toast.*restartPending, compact.languageRestart.*,
settings.button.restartNow, settings.journal.*, diagnostics.field.*,
diagnostics.check.*, diagnostics.outcome.*, diagnostics.languagePendingRestart,
diagnostics.report.title).

Mirrors the technique used for compact.miniLog.collapse in feature 003:
insert new "key": "value" lines just before the final closing brace, so
existing key order/formatting is untouched and the parity test
(LocalizationServiceTests.EveryShippedLanguage_HasNonEmptyTable_WithSameKeySetAsRussian)
passes for every language. Idempotent — skips keys that already exist.
#>

$ErrorActionPreference = 'Stop'
$root = "c:\Users\adm\Desktop\13\vibe\Steamoff\src\Steamoff.Core\Resources\Localization"
$languages = @('ru','en','de','fr','es','it','pt','pl','zh')

# Ordered list of (key, @{ lang = text }) pairs.
$entries = New-Object System.Collections.ArrayList
function Add-Entry([string]$key, [hashtable]$texts) {
    [void]$entries.Add(@{ Key = $key; Texts = $texts })
}

# ---------- log.event.* ----------
Add-Entry 'log.event.appStarted' @{ ru='Приложение запущено'; en='Application started'; de='Anwendung gestartet'; fr='Application démarrée'; es='Aplicación iniciada'; it='Applicazione avviata'; pt='Aplicativo iniciado'; pl='Aplikacja uruchomiona'; zh='应用程序已启动' }
Add-Entry 'log.event.appClosed' @{ ru='Приложение закрыто'; en='Application closed'; de='Anwendung beendet'; fr='Application fermée'; es='Aplicación cerrada'; it='Applicazione chiusa'; pt='Aplicativo encerrado'; pl='Aplikacja zamknięta'; zh='应用程序已关闭' }
Add-Entry 'log.event.settingsOpened' @{ ru='Открыты настройки'; en='Settings opened'; de='Einstellungen geöffnet'; fr='Paramètres ouverts'; es='Ajustes abiertos'; it='Impostazioni aperte'; pt='Configurações abertas'; pl='Otwarto ustawienia'; zh='已打开设置' }
Add-Entry 'log.event.settingsApplied' @{ ru='Настройки применены'; en='Settings applied'; de='Einstellungen übernommen'; fr='Paramètres appliqués'; es='Ajustes aplicados'; it='Impostazioni applicate'; pt='Configurações aplicadas'; pl='Ustawienia zastosowane'; zh='设置已应用' }
Add-Entry 'log.event.settingsSaved' @{ ru='Настройки сохранены'; en='Settings saved'; de='Einstellungen gespeichert'; fr='Paramètres enregistrés'; es='Ajustes guardados'; it='Impostazioni salvate'; pt='Configurações salvas'; pl='Ustawienia zapisane'; zh='设置已保存' }
Add-Entry 'log.event.settingsCancelled' @{ ru='Изменения настроек отменены'; en='Settings changes cancelled'; de='Änderungen an den Einstellungen verworfen'; fr='Modifications des paramètres annulées'; es='Cambios de ajustes cancelados'; it='Modifiche alle impostazioni annullate'; pt='Alterações de configurações canceladas'; pl='Anulowano zmiany ustawień'; zh='已取消设置更改' }
Add-Entry 'log.event.languageChangedRestartRequired' @{ ru='Выбран новый язык. Для полного применения требуется перезапуск'; en='New language selected. Restart is required to fully apply it'; de='Neue Sprache ausgewählt. Ein Neustart ist erforderlich, um sie vollständig zu übernehmen'; fr="Nouvelle langue sélectionnée. Un redémarrage est nécessaire pour l'appliquer complètement"; es='Nuevo idioma seleccionado. Es necesario reiniciar para aplicarlo por completo'; it='Nuova lingua selezionata. È necessario riavviare per applicarla completamente'; pt='Novo idioma selecionado. É necessário reiniciar para aplicá-lo totalmente'; pl='Wybrano nowy język. Aby w pełni go zastosować, wymagany jest restart'; zh='已选择新语言。需要重启才能完全应用' }
Add-Entry 'log.event.restartRequested' @{ ru='Запрошен перезапуск приложения'; en='Application restart requested'; de='Neustart der Anwendung angefordert'; fr="Redémarrage de l'application demandé"; es='Reinicio de la aplicación solicitado'; it="Riavvio dell'applicazione richiesto"; pt='Reinício do aplicativo solicitado'; pl='Zażądano ponownego uruchomienia aplikacji'; zh='已请求重启应用程序' }
Add-Entry 'log.event.restartFailed' @{ ru='Не удалось перезапустить приложение: {0}'; en='Failed to restart the application: {0}'; de='Neustart der Anwendung fehlgeschlagen: {0}'; fr="Échec du redémarrage de l'application : {0}"; es='No se pudo reiniciar la aplicación: {0}'; it="Riavvio dell'applicazione non riuscito: {0}"; pt='Falha ao reiniciar o aplicativo: {0}'; pl='Nie udało się ponownie uruchomić aplikacji: {0}'; zh='应用程序重启失败：{0}' }
Add-Entry 'log.event.steamAutoSearchStarted' @{ ru='Запущен автопоиск Steam'; en='Steam auto-search started'; de='Automatische Steam-Suche gestartet'; fr='Recherche automatique de Steam démarrée'; es='Búsqueda automática de Steam iniciada'; it='Ricerca automatica di Steam avviata'; pt='Busca automática do Steam iniciada'; pl='Rozpoczęto automatyczne wyszukiwanie Steam'; zh='已开始自动搜索 Steam' }
Add-Entry 'log.event.steamAutoSearchSucceeded' @{ ru='Steam найден автоматически: {0}'; en='Steam found automatically: {0}'; de='Steam automatisch gefunden: {0}'; fr='Steam trouvé automatiquement : {0}'; es='Steam encontrado automáticamente: {0}'; it='Steam trovato automaticamente: {0}'; pt='Steam encontrado automaticamente: {0}'; pl='Automatycznie znaleziono Steam: {0}'; zh='已自动找到 Steam：{0}' }
Add-Entry 'log.event.steamAutoSearchFailed' @{ ru='Автопоиск Steam не дал результата'; en='Steam auto-search did not find anything'; de='Die automatische Steam-Suche hat nichts gefunden'; fr="La recherche automatique de Steam n'a rien trouvé"; es='La búsqueda automática de Steam no encontró nada'; it='La ricerca automatica di Steam non ha trovato nulla'; pt='A busca automática do Steam não encontrou nada'; pl='Automatyczne wyszukiwanie Steam nie znalazło niczego'; zh='自动搜索 Steam 未找到任何内容' }
Add-Entry 'log.event.steamPathNormalized' @{ ru='Путь к Steam нормализован: {0} → {1}'; en='Steam path normalized: {0} → {1}'; de='Steam-Pfad normalisiert: {0} → {1}'; fr='Chemin de Steam normalisé : {0} → {1}'; es='Ruta de Steam normalizada: {0} → {1}'; it='Percorso di Steam normalizzato: {0} → {1}'; pt='Caminho do Steam normalizado: {0} → {1}'; pl='Znormalizowano ścieżkę Steam: {0} → {1}'; zh='Steam 路径已规范化：{0} → {1}' }
Add-Entry 'log.event.steamPathInvalid' @{ ru='Указанный путь к Steam недействителен: {0}'; en='The specified Steam path is invalid: {0}'; de='Der angegebene Steam-Pfad ist ungültig: {0}'; fr='Le chemin Steam indiqué n''est pas valide : {0}'; es='La ruta de Steam especificada no es válida: {0}'; it='Il percorso di Steam specificato non è valido: {0}'; pt='O caminho do Steam especificado é inválido: {0}'; pl='Podana ścieżka Steam jest nieprawidłowa: {0}'; zh='指定的 Steam 路径无效：{0}' }
Add-Entry 'log.event.folderAdded' @{ ru='Добавлена папка: {0}'; en='Folder added: {0}'; de='Ordner hinzugefügt: {0}'; fr='Dossier ajouté : {0}'; es='Carpeta añadida: {0}'; it='Cartella aggiunta: {0}'; pt='Pasta adicionada: {0}'; pl='Dodano folder: {0}'; zh='已添加文件夹：{0}' }
Add-Entry 'log.event.folderRemoved' @{ ru='Удалена папка: {0}'; en='Folder removed: {0}'; de='Ordner entfernt: {0}'; fr='Dossier supprimé : {0}'; es='Carpeta eliminada: {0}'; it='Cartella rimossa: {0}'; pt='Pasta removida: {0}'; pl='Usunięto folder: {0}'; zh='已移除文件夹：{0}' }
Add-Entry 'log.event.exeAdded' @{ ru='Добавлен исполняемый файл: {0}'; en='Executable added: {0}'; de='Ausführbare Datei hinzugefügt: {0}'; fr='Exécutable ajouté : {0}'; es='Ejecutable añadido: {0}'; it='Eseguibile aggiunto: {0}'; pt='Executável adicionado: {0}'; pl='Dodano plik wykonywalny: {0}'; zh='已添加可执行文件：{0}' }
Add-Entry 'log.event.exeRemoved' @{ ru='Удалён исполняемый файл: {0}'; en='Executable removed: {0}'; de='Ausführbare Datei entfernt: {0}'; fr='Exécutable supprimé : {0}'; es='Ejecutable eliminado: {0}'; it='Eseguibile rimosso: {0}'; pt='Executável removido: {0}'; pl='Usunięto plik wykonywalny: {0}'; zh='已移除可执行文件：{0}' }
Add-Entry 'log.event.firewallBlockStarted' @{ ru='Начата блокировка через брандмауэр'; en='Firewall block started'; de='Blockierung über die Firewall gestartet'; fr='Blocage par le pare-feu démarré'; es='Bloqueo por el firewall iniciado'; it='Blocco tramite firewall avviato'; pt='Bloqueio pelo firewall iniciado'; pl='Rozpoczęto blokowanie przez zaporę'; zh='已开始通过防火墙阻止' }
Add-Entry 'log.event.firewallBlockCompleted' @{ ru='Блокировка через брандмауэр завершена'; en='Firewall block completed'; de='Blockierung über die Firewall abgeschlossen'; fr='Blocage par le pare-feu terminé'; es='Bloqueo por el firewall completado'; it='Blocco tramite firewall completato'; pt='Bloqueio pelo firewall concluído'; pl='Zakończono blokowanie przez zaporę'; zh='防火墙阻止已完成' }
Add-Entry 'log.event.firewallBlockFailed' @{ ru='Не удалось выполнить блокировку через брандмауэр: {0}'; en='Firewall block failed: {0}'; de='Blockierung über die Firewall fehlgeschlagen: {0}'; fr='Échec du blocage par le pare-feu : {0}'; es='Error al bloquear mediante el firewall: {0}'; it='Blocco tramite firewall non riuscito: {0}'; pt='Falha no bloqueio pelo firewall: {0}'; pl='Blokowanie przez zaporę nie powiodło się: {0}'; zh='防火墙阻止失败：{0}' }
Add-Entry 'log.event.firewallUnblockStarted' @{ ru='Начата отмена блокировки через брандмауэр'; en='Firewall unblock started'; de='Aufhebung der Blockierung über die Firewall gestartet'; fr='Déblocage par le pare-feu démarré'; es='Desbloqueo por el firewall iniciado'; it='Sblocco tramite firewall avviato'; pt='Desbloqueio pelo firewall iniciado'; pl='Rozpoczęto odblokowywanie przez zaporę'; zh='已开始通过防火墙解除阻止' }
Add-Entry 'log.event.firewallUnblockCompleted' @{ ru='Отмена блокировки через брандмауэр завершена'; en='Firewall unblock completed'; de='Aufhebung der Blockierung über die Firewall abgeschlossen'; fr='Déblocage par le pare-feu terminé'; es='Desbloqueo por el firewall completado'; it='Sblocco tramite firewall completato'; pt='Desbloqueio pelo firewall concluído'; pl='Zakończono odblokowywanie przez zaporę'; zh='防火墙解除阻止已完成' }
Add-Entry 'log.event.firewallUnblockFailed' @{ ru='Не удалось отменить блокировку через брандмауэр: {0}'; en='Firewall unblock failed: {0}'; de='Aufhebung der Blockierung über die Firewall fehlgeschlagen: {0}'; fr='Échec du déblocage par le pare-feu : {0}'; es='Error al desbloquear mediante el firewall: {0}'; it='Sblocco tramite firewall non riuscito: {0}'; pt='Falha no desbloqueio pelo firewall: {0}'; pl='Odblokowywanie przez zaporę nie powiodło się: {0}'; zh='防火墙解除阻止失败：{0}' }
Add-Entry 'log.event.driftDetected' @{ ru='Обнаружено расхождение между ожидаемым и фактическим состоянием правил'; en='Drift detected between expected and actual rule state'; de='Abweichung zwischen erwartetem und tatsächlichem Regelstatus festgestellt'; fr="Écart détecté entre l'état attendu et l'état réel des règles"; es='Se detectó una discrepancia entre el estado esperado y el real de las reglas'; it='Rilevata una discrepanza tra lo stato atteso e quello effettivo delle regole'; pt='Detectada divergência entre o estado esperado e o estado real das regras'; pl='Wykryto rozbieżność między oczekiwanym a rzeczywistym stanem reguł'; zh='检测到预期规则状态与实际状态不一致' }
Add-Entry 'log.event.autostartCreated' @{ ru='Включён автозапуск'; en='Autostart enabled'; de='Autostart aktiviert'; fr='Démarrage automatique activé'; es='Inicio automático activado'; it='Avvio automatico abilitato'; pt='Inicialização automática ativada'; pl='Włączono autostart'; zh='已启用自动启动' }
Add-Entry 'log.event.autostartRemoved' @{ ru='Отключён автозапуск'; en='Autostart disabled'; de='Autostart deaktiviert'; fr='Démarrage automatique désactivé'; es='Inicio automático desactivado'; it='Avvio automatico disabilitato'; pt='Inicialização automática desativada'; pl='Wyłączono autostart'; zh='已禁用自动启动' }
Add-Entry 'log.event.diagnosticsCopied' @{ ru='Отчёт диагностики скопирован в буфер обмена'; en='Diagnostics report copied to clipboard'; de='Diagnosebericht in die Zwischenablage kopiert'; fr='Rapport de diagnostic copié dans le presse-papiers'; es='Informe de diagnóstico copiado al portapapeles'; it='Rapporto diagnostico copiato negli appunti'; pt='Relatório de diagnóstico copiado para a área de transferência'; pl='Skopiowano raport diagnostyczny do schowka'; zh='诊断报告已复制到剪贴板' }
Add-Entry 'log.event.releaseBuildStarted' @{ ru='Начата сборка релиза'; en='Release build started'; de='Release-Build gestartet'; fr='Compilation de la version de diffusion démarrée'; es='Compilación de la versión de lanzamiento iniciada'; it='Compilazione della versione di rilascio avviata'; pt='Compilação da versão de lançamento iniciada'; pl='Rozpoczęto kompilację wydania'; zh='已开始构建发布版本' }
Add-Entry 'log.event.releaseBuildCompleted' @{ ru='Сборка релиза завершена'; en='Release build completed'; de='Release-Build abgeschlossen'; fr='Compilation de la version de diffusion terminée'; es='Compilación de la versión de lanzamiento completada'; it='Compilazione della versione di rilascio completata'; pt='Compilação da versão de lançamento concluída'; pl='Zakończono kompilację wydania'; zh='发布版本构建已完成' }
Add-Entry 'log.event.releaseBuildFailed' @{ ru='Сборка релиза завершилась с ошибкой: {0}'; en='Release build failed: {0}'; de='Release-Build fehlgeschlagen: {0}'; fr='Échec de la compilation de la version de diffusion : {0}'; es='Error en la compilación de la versión de lanzamiento: {0}'; it='Compilazione della versione di rilascio non riuscita: {0}'; pt='Falha na compilação da versão de lançamento: {0}'; pl='Kompilacja wydania nie powiodła się: {0}'; zh='发布版本构建失败：{0}' }

# ---------- restart UI ----------
Add-Entry 'settings.language.restartWarning' @{ ru='Для полного применения языка перезапустите Steamoff.'; en='Restart Steamoff to fully apply the language change.'; de='Starten Sie Steamoff neu, um die Sprachänderung vollständig zu übernehmen.'; fr='Redémarrez Steamoff pour appliquer entièrement le changement de langue.'; es='Reinicia Steamoff para aplicar por completo el cambio de idioma.'; it='Riavvia Steamoff per applicare completamente il cambio di lingua.'; pt='Reinicie o Steamoff para aplicar totalmente a alteração de idioma.'; pl='Uruchom ponownie Steamoff, aby w pełni zastosować zmianę języka.'; zh='请重启 Steamoff 以完全应用语言更改。' }
Add-Entry 'settings.toast.appliedRestartPending' @{ ru='Настройки применены. Для смены языка требуется перезапуск.'; en='Settings applied. A restart is required to change the language.'; de='Einstellungen übernommen. Für den Sprachwechsel ist ein Neustart erforderlich.'; fr='Paramètres appliqués. Un redémarrage est nécessaire pour changer la langue.'; es='Ajustes aplicados. Es necesario reiniciar para cambiar el idioma.'; it='Impostazioni applicate. È necessario riavviare per cambiare lingua.'; pt='Configurações aplicadas. É necessário reiniciar para alterar o idioma.'; pl='Ustawienia zastosowane. Aby zmienić język, wymagany jest restart.'; zh='设置已应用。更改语言需要重启。' }
Add-Entry 'settings.toast.savedRestartPending' @{ ru='Требуется перезапуск для смены языка.'; en='A restart is required to change the language.'; de='Für den Sprachwechsel ist ein Neustart erforderlich.'; fr='Un redémarrage est nécessaire pour changer la langue.'; es='Es necesario reiniciar para cambiar el idioma.'; it='È necessario riavviare per cambiare lingua.'; pt='É necessário reiniciar para alterar o idioma.'; pl='Wymagany jest restart, aby zmienić język.'; zh='更改语言需要重启。' }
Add-Entry 'settings.toast.restartFailed' @{ ru='Не удалось перезапустить Steamoff. Подробности в журнале.'; en="Couldn't restart Steamoff. See the log for details."; de='Steamoff konnte nicht neu gestartet werden. Details im Protokoll.'; fr='Impossible de redémarrer Steamoff. Voir le journal pour plus de détails.'; es='No se pudo reiniciar Steamoff. Consulta el registro para más detalles.'; it='Impossibile riavviare Steamoff. Vedere il registro per i dettagli.'; pt='Não foi possível reiniciar o Steamoff. Veja o log para mais detalhes.'; pl='Nie udało się ponownie uruchomić Steamoff. Szczegóły w dzienniku.'; zh='无法重启 Steamoff。详情请查看日志。' }
Add-Entry 'compact.languageRestart.banner' @{ ru='Требуется перезапуск для смены языка.'; en='Restart required to change the language.'; de='Neustart erforderlich, um die Sprache zu ändern.'; fr='Redémarrage nécessaire pour changer la langue.'; es='Es necesario reiniciar para cambiar el idioma.'; it='È necessario riavviare per cambiare lingua.'; pt='É necessário reiniciar para alterar o idioma.'; pl='Wymagany restart, aby zmienić język.'; zh='更改语言需要重启。' }
Add-Entry 'settings.button.restartNow' @{ ru='Перезапустить сейчас'; en='Restart now'; de='Jetzt neu starten'; fr='Redémarrer maintenant'; es='Reiniciar ahora'; it='Riavvia ora'; pt='Reiniciar agora'; pl='Uruchom ponownie teraz'; zh='立即重启' }

# ---------- journal panel ----------
Add-Entry 'settings.journal.title' @{ ru='Журнал'; en='Log'; de='Protokoll'; fr='Journal'; es='Registro'; it='Registro'; pt='Registro'; pl='Dziennik'; zh='日志' }
Add-Entry 'settings.journal.filter.all' @{ ru='Все'; en='All'; de='Alle'; fr='Tous'; es='Todos'; it='Tutti'; pt='Todos'; pl='Wszystkie'; zh='全部' }
Add-Entry 'settings.journal.filter.errors' @{ ru='Ошибки'; en='Errors'; de='Fehler'; fr='Erreurs'; es='Errores'; it='Errori'; pt='Erros'; pl='Błędy'; zh='错误' }
Add-Entry 'settings.journal.filter.warnings' @{ ru='Предупреждения'; en='Warnings'; de='Warnungen'; fr='Avertissements'; es='Advertencias'; it='Avvisi'; pt='Avisos'; pl='Ostrzeżenia'; zh='警告' }
Add-Entry 'settings.journal.filter.info' @{ ru='Информация'; en='Info'; de='Information'; fr='Infos'; es='Información'; it='Informazioni'; pt='Informações'; pl='Informacje'; zh='信息' }
Add-Entry 'settings.journal.refresh' @{ ru='Обновить'; en='Refresh'; de='Aktualisieren'; fr='Actualiser'; es='Actualizar'; it='Aggiorna'; pt='Atualizar'; pl='Odśwież'; zh='刷新' }
Add-Entry 'settings.journal.openFolder' @{ ru='Открыть папку логов'; en='Open log folder'; de='Protokollordner öffnen'; fr='Ouvrir le dossier des journaux'; es='Abrir carpeta de registros'; it='Apri cartella dei log'; pt='Abrir pasta de logs'; pl='Otwórz folder dzienników'; zh='打开日志文件夹' }
Add-Entry 'settings.journal.copyDiagnostics' @{ ru='Скопировать диагностику'; en='Copy diagnostics'; de='Diagnose kopieren'; fr='Copier le diagnostic'; es='Copiar diagnóstico'; it='Copia diagnostica'; pt='Copiar diagnóstico'; pl='Kopiuj diagnostykę'; zh='复制诊断信息' }
Add-Entry 'settings.journal.clearDisplay' @{ ru='Очистить отображение'; en='Clear display'; de='Anzeige leeren'; fr="Effacer l'affichage"; es='Borrar visualización'; it='Cancella visualizzazione'; pt='Limpar exibição'; pl='Wyczyść widok'; zh='清除显示' }
Add-Entry 'settings.journal.empty' @{ ru='Записей пока нет.'; en='No entries yet.'; de='Noch keine Einträge.'; fr="Pas encore d'entrées."; es='Aún no hay entradas.'; it='Ancora nessuna voce.'; pt='Ainda não há entradas.'; pl='Brak wpisów.'; zh='暂无记录。' }
Add-Entry 'settings.journal.cleared' @{ ru='Отображение журнала очищено (файл лога не изменён).'; en='Log display cleared (the log file is untouched).'; de='Protokollanzeige geleert (Protokolldatei bleibt unverändert).'; fr='Affichage du journal effacé (le fichier journal reste intact).'; es='Visualización del registro borrada (el archivo de registro no se modifica).'; it='Visualizzazione del registro cancellata (il file di log resta invariato).'; pt='Exibição do log limpa (o arquivo de log permanece intacto).'; pl='Wyczyszczono widok dziennika (plik dziennika pozostaje bez zmian).'; zh='日志显示已清除（日志文件未更改）。' }

# ---------- diagnostics fields & report ----------
Add-Entry 'diagnostics.field.appVersion' @{ ru='Версия приложения'; en='Application version'; de='Anwendungsversion'; fr="Version de l'application"; es='Versión de la aplicación'; it="Versione dell'applicazione"; pt='Versão do aplicativo'; pl='Wersja aplikacji'; zh='应用程序版本' }
Add-Entry 'diagnostics.field.currentLanguage' @{ ru='Текущий язык'; en='Current language'; de='Aktuelle Sprache'; fr='Langue actuelle'; es='Idioma actual'; it='Lingua attuale'; pt='Idioma atual'; pl='Bieżący język'; zh='当前语言' }
Add-Entry 'diagnostics.field.selectedLanguage' @{ ru='Выбранный язык'; en='Selected language'; de='Ausgewählte Sprache'; fr='Langue sélectionnée'; es='Idioma seleccionado'; it='Lingua selezionata'; pt='Idioma selecionado'; pl='Wybrany język'; zh='已选择的语言' }
Add-Entry 'diagnostics.field.restartRequired' @{ ru='Требуется перезапуск'; en='Restart required'; de='Neustart erforderlich'; fr='Redémarrage nécessaire'; es='Reinicio necesario'; it='Riavvio necessario'; pt='Reinício necessário'; pl='Wymagany restart'; zh='需要重启' }
Add-Entry 'diagnostics.field.windowsUser' @{ ru='Пользователь Windows'; en='Windows user'; de='Windows-Benutzer'; fr='Utilisateur Windows'; es='Usuario de Windows'; it='Utente Windows'; pt='Usuário do Windows'; pl='Użytkownik Windows'; zh='Windows 用户' }
Add-Entry 'diagnostics.field.elevated' @{ ru='Права администратора'; en='Administrator rights'; de='Administratorrechte'; fr='Droits administrateur'; es='Derechos de administrador'; it='Diritti di amministratore'; pt='Direitos de administrador'; pl='Uprawnienia administratora'; zh='管理员权限' }
Add-Entry 'diagnostics.field.settingsPath' @{ ru='Путь к файлу настроек'; en='Settings file path'; de='Pfad zur Einstellungsdatei'; fr='Chemin du fichier de paramètres'; es='Ruta del archivo de ajustes'; it='Percorso del file delle impostazioni'; pt='Caminho do arquivo de configurações'; pl='Ścieżka pliku ustawień'; zh='设置文件路径' }
Add-Entry 'diagnostics.field.logPath' @{ ru='Путь к файлу журнала'; en='Log file path'; de='Pfad zur Protokolldatei'; fr='Chemin du fichier journal'; es='Ruta del archivo de registro'; it='Percorso del file di registro'; pt='Caminho do arquivo de log'; pl='Ścieżka pliku dziennika'; zh='日志文件路径' }
Add-Entry 'diagnostics.field.steamPath' @{ ru='Путь к Steam'; en='Steam path'; de='Steam-Pfad'; fr='Chemin de Steam'; es='Ruta de Steam'; it='Percorso di Steam'; pt='Caminho do Steam'; pl='Ścieżka Steam'; zh='Steam 路径' }
Add-Entry 'diagnostics.field.steamPathValid' @{ ru='Путь к Steam действителен'; en='Steam path is valid'; de='Steam-Pfad ist gültig'; fr='Le chemin de Steam est valide'; es='La ruta de Steam es válida'; it='Il percorso di Steam è valido'; pt='O caminho do Steam é válido'; pl='Ścieżka Steam jest prawidłowa'; zh='Steam 路径有效' }
Add-Entry 'diagnostics.field.additionalFolderCount' @{ ru='Количество дополнительных папок'; en='Additional folders count'; de='Anzahl zusätzlicher Ordner'; fr='Nombre de dossiers supplémentaires'; es='Número de carpetas adicionales'; it='Numero di cartelle aggiuntive'; pt='Número de pastas adicionais'; pl='Liczba dodatkowych folderów'; zh='附加文件夹数量' }
Add-Entry 'diagnostics.field.separateExeCount' @{ ru='Количество отдельных EXE-файлов'; en='Separate executables count'; de='Anzahl separater ausführbarer Dateien'; fr="Nombre d'exécutables séparés"; es='Número de ejecutables independientes'; it='Numero di eseguibili separati'; pt='Número de executáveis separados'; pl='Liczba oddzielnych plików wykonywalnych'; zh='单独可执行文件数量' }
Add-Entry 'diagnostics.field.firewallDesired' @{ ru='Желаемое состояние брандмауэра'; en='Desired firewall state'; de='Gewünschter Firewall-Status'; fr='État de pare-feu souhaité'; es='Estado deseado del firewall'; it='Stato firewall desiderato'; pt='Estado desejado do firewall'; pl='Pożądany stan zapory'; zh='期望的防火墙状态' }
Add-Entry 'diagnostics.field.firewallActual' @{ ru='Фактическое состояние брандмауэра'; en='Actual firewall state'; de='Tatsächlicher Firewall-Status'; fr='État de pare-feu réel'; es='Estado real del firewall'; it='Stato firewall effettivo'; pt='Estado real do firewall'; pl='Rzeczywisty stan zapory'; zh='实际防火墙状态' }
Add-Entry 'diagnostics.field.driftStatus' @{ ru='Статус расхождения'; en='Drift status'; de='Abweichungsstatus'; fr="État de l'écart"; es='Estado de discrepancia'; it='Stato di discrepanza'; pt='Estado de divergência'; pl='Stan rozbieżności'; zh='偏差状态' }
Add-Entry 'diagnostics.field.autostartStatus' @{ ru='Статус автозапуска'; en='Autostart status'; de='Autostart-Status'; fr='État du démarrage automatique'; es='Estado del inicio automático'; it="Stato dell'avvio automatico"; pt='Estado da inicialização automática'; pl='Stan autostartu'; zh='自动启动状态' }
Add-Entry 'diagnostics.field.lastTestResult' @{ ru='Результат последней проверки'; en='Last test result'; de='Letztes Testergebnis'; fr='Résultat du dernier test'; es='Resultado de la última prueba'; it="Risultato dell'ultimo test"; pt='Resultado do último teste'; pl='Wynik ostatniego testu'; zh='上次测试结果' }
Add-Entry 'diagnostics.field.lastReleaseBuildPath' @{ ru='Путь последней сборки релиза'; en='Last release build path'; de='Pfad des letzten Release-Builds'; fr='Chemin de la dernière compilation de version'; es='Ruta de la última compilación de lanzamiento'; it="Percorso dell'ultima build di rilascio"; pt='Caminho da última compilação de lançamento'; pl='Ścieżka ostatniej kompilacji wydania'; zh='上次发布构建路径' }
Add-Entry 'diagnostics.field.notAvailable' @{ ru='нет данных'; en='not available'; de='nicht verfügbar'; fr='non disponible'; es='no disponible'; it='non disponibile'; pt='não disponível'; pl='brak danych'; zh='不可用' }
Add-Entry 'diagnostics.languagePendingRestart' @{ ru='Выбран новый язык: {0}. Он будет применён после перезапуска.'; en='New language selected: {0}. It will be applied after restart.'; de='Neue Sprache ausgewählt: {0}. Sie wird nach dem Neustart angewendet.'; fr='Nouvelle langue sélectionnée : {0}. Elle sera appliquée après le redémarrage.'; es='Nuevo idioma seleccionado: {0}. Se aplicará después de reiniciar.'; it='Nuova lingua selezionata: {0}. Verrà applicata dopo il riavvio.'; pt='Novo idioma selecionado: {0}. Será aplicado após reiniciar.'; pl='Wybrano nowy język: {0}. Zostanie zastosowany po ponownym uruchomieniu.'; zh='已选择新语言：{0}。重启后将生效。' }
Add-Entry 'diagnostics.report.title' @{ ru='=== Отчёт диагностики Steamoff ==='; en='=== Steamoff Diagnostics Report ==='; de='=== Steamoff-Diagnosebericht ==='; fr='=== Rapport de diagnostic Steamoff ==='; es='=== Informe de diagnóstico de Steamoff ==='; it='=== Rapporto diagnostico di Steamoff ==='; pt='=== Relatório de diagnóstico do Steamoff ==='; pl='=== Raport diagnostyczny Steamoff ==='; zh='=== Steamoff 诊断报告 ===' }
Add-Entry 'diagnostics.outcome.success' @{ ru='Тестирование завершено успешно'; en='Testing completed successfully'; de='Test erfolgreich abgeschlossen'; fr='Test terminé avec succès'; es='Prueba completada con éxito'; it='Test completato con successo'; pt='Teste concluído com sucesso'; pl='Test zakończony pomyślnie'; zh='测试成功完成' }
Add-Entry 'diagnostics.outcome.warning' @{ ru='Тестирование завершено с предупреждением'; en='Testing completed with a warning'; de='Test mit Warnung abgeschlossen'; fr='Test terminé avec un avertissement'; es='Prueba completada con una advertencia'; it='Test completato con un avviso'; pt='Teste concluído com um aviso'; pl='Test zakończony z ostrzeżeniem'; zh='测试完成但有警告' }
Add-Entry 'diagnostics.outcome.error' @{ ru='Тестирование завершено с ошибкой'; en='Testing completed with an error'; de='Test mit Fehler abgeschlossen'; fr='Test terminé avec une erreur'; es='Prueba completada con un error'; it='Test completato con un errore'; pt='Teste concluído com um erro'; pl='Test zakończony błędem'; zh='测试完成但有错误' }

# ---------- diagnostics.check.* ----------
Add-Entry 'diagnostics.check.elevation.title' @{ ru='Права администратора'; en='Admin / Elevation'; de='Administratorrechte'; fr='Droits administrateur'; es='Derechos de administrador'; it='Diritti di amministratore'; pt='Direitos de administrador'; pl='Uprawnienia administratora'; zh='管理员权限' }
Add-Entry 'diagnostics.check.elevation.ok' @{ ru='Приложение запущено с правами администратора — операции с firewall доступны.'; en='The application is running with administrator rights — firewall operations are available.'; de='Die Anwendung läuft mit Administratorrechten — Firewall-Operationen sind verfügbar.'; fr="L'application s'exécute avec des droits administrateur — les opérations de pare-feu sont disponibles."; es='La aplicación se ejecuta con derechos de administrador: las operaciones del firewall están disponibles.'; it="L'applicazione è in esecuzione con diritti di amministratore: le operazioni sul firewall sono disponibili."; pt='O aplicativo está em execução com direitos de administrador — as operações de firewall estão disponíveis.'; pl='Aplikacja działa z uprawnieniami administratora — operacje zapory są dostępne.'; zh='应用程序以管理员权限运行——可以执行防火墙操作。' }
Add-Entry 'diagnostics.check.elevation.error' @{ ru='Нет прав администратора — операции с firewall недоступны (режим только для чтения).'; en='No administrator rights — firewall operations are unavailable (read-only mode).'; de='Keine Administratorrechte — Firewall-Operationen sind nicht verfügbar (Nur-Lese-Modus).'; fr='Aucun droit administrateur — les opérations de pare-feu ne sont pas disponibles (mode lecture seule).'; es='Sin derechos de administrador: las operaciones del firewall no están disponibles (modo de solo lectura).'; it='Nessun diritto di amministratore: le operazioni sul firewall non sono disponibili (modalità di sola lettura).'; pt='Sem direitos de administrador — as operações de firewall não estão disponíveis (modo somente leitura).'; pl='Brak uprawnień administratora — operacje zapory są niedostępne (tryb tylko do odczytu).'; zh='没有管理员权限——无法执行防火墙操作（只读模式）。' }
Add-Entry 'diagnostics.check.settingsLabel' @{ ru='settings.json'; en='settings.json'; de='settings.json'; fr='settings.json'; es='settings.json'; it='settings.json'; pt='settings.json'; pl='settings.json'; zh='settings.json' }
Add-Entry 'diagnostics.check.logLabel' @{ ru='журнал'; en='log'; de='Protokoll'; fr='journal'; es='registro'; it='registro'; pt='log'; pl='dziennik'; zh='日志' }
Add-Entry 'diagnostics.check.pathAccess.ok' @{ ru='Каталог доступен для записи: {0}'; en='The directory is writable: {0}'; de='Das Verzeichnis ist beschreibbar: {0}'; fr="Le répertoire est accessible en écriture : {0}"; es='El directorio admite escritura: {0}'; it='La cartella è scrivibile: {0}'; pt='O diretório é gravável: {0}'; pl='Katalog jest zapisywalny: {0}'; zh='目录可写：{0}' }
Add-Entry 'diagnostics.check.pathAccess.fallback' @{ ru='Каталог доступен, но используется резервное расположение: {0}'; en='The directory is accessible, but a fallback location is being used: {0}'; de='Das Verzeichnis ist verfügbar, es wird jedoch ein Ausweichort verwendet: {0}'; fr='Le répertoire est accessible, mais un emplacement de secours est utilisé : {0}'; es='El directorio es accesible, pero se está usando una ubicación de reserva: {0}'; it='La cartella è accessibile, ma viene usata una posizione di riserva: {0}'; pt='O diretório está acessível, mas está sendo usado um local alternativo: {0}'; pl='Katalog jest dostępny, ale używana jest lokalizacja zapasowa: {0}'; zh='目录可访问，但正在使用备用位置：{0}' }
Add-Entry 'diagnostics.check.pathAccess.notFound' @{ ru='Каталог не найден или недоступен: {0}'; en='The directory was not found or is inaccessible: {0}'; de='Das Verzeichnis wurde nicht gefunden oder ist nicht zugänglich: {0}'; fr='Le répertoire est introuvable ou inaccessible : {0}'; es='No se encontró el directorio o no es accesible: {0}'; it='La cartella non è stata trovata o non è accessibile: {0}'; pt='O diretório não foi encontrado ou está inacessível: {0}'; pl='Nie znaleziono katalogu lub jest niedostępny: {0}'; zh='未找到目录或无法访问：{0}' }
Add-Entry 'diagnostics.check.pathAccess.error' @{ ru="Не удалось проверить доступ к '{0}': {1}"; en="Couldn't check access to '{0}': {1}"; de="Der Zugriff auf '{0}' konnte nicht geprüft werden: {1}"; fr='Impossible de vérifier l''accès à « {0} » : {1}'; es='No se pudo comprobar el acceso a «{0}»: {1}'; it='Impossibile verificare l''accesso a "{0}": {1}'; pt="Não foi possível verificar o acesso a '{0}': {1}"; pl='Nie udało się sprawdzić dostępu do „{0}”: {1}'; zh='无法检查对 "{0}" 的访问权限：{1}' }
Add-Entry 'diagnostics.check.steam.title' @{ ru='Steam'; en='Steam'; de='Steam'; fr='Steam'; es='Steam'; it='Steam'; pt='Steam'; pl='Steam'; zh='Steam' }
Add-Entry 'diagnostics.check.steam.found' @{ ru='Steam найден: {0} (источник: {1}).'; en='Steam found: {0} (source: {1}).'; de='Steam gefunden: {0} (Quelle: {1}).'; fr='Steam trouvé : {0} (source : {1}).'; es='Steam encontrado: {0} (fuente: {1}).'; it='Steam trovato: {0} (fonte: {1}).'; pt='Steam encontrado: {0} (fonte: {1}).'; pl='Znaleziono Steam: {0} (źródło: {1}).'; zh='已找到 Steam：{0}（来源：{1}）。' }
Add-Entry 'diagnostics.check.steam.notFound' @{ ru='Steam не найден автоматически. Укажите путь вручную в настройках.'; en='Steam was not found automatically. Specify the path manually in Settings.'; de='Steam wurde nicht automatisch gefunden. Geben Sie den Pfad manuell in den Einstellungen an.'; fr='Steam n''a pas été trouvé automatiquement. Indiquez le chemin manuellement dans les paramètres.'; es='Steam no se encontró automáticamente. Especifica la ruta manualmente en los ajustes.'; it='Steam non è stato trovato automaticamente. Specifica il percorso manualmente nelle impostazioni.'; pt='O Steam não foi encontrado automaticamente. Especifique o caminho manualmente nas configurações.'; pl='Nie znaleziono automatycznie Steam. Podaj ścieżkę ręcznie w ustawieniach.'; zh='未能自动找到 Steam。请在设置中手动指定路径。' }
Add-Entry 'diagnostics.check.steamCore.title' @{ ru='Ядро Steam'; en='Steam Core'; de='Steam-Kern'; fr='Cœur de Steam'; es='Núcleo de Steam'; it='Nucleo di Steam'; pt='Núcleo do Steam'; pl='Rdzeń Steam'; zh='Steam 核心' }
Add-Entry 'diagnostics.check.steamCore.found' @{ ru='Найдено исполняемых файлов ядра Steam: {0}.'; en='Steam core executables found: {0}.'; de='Gefundene Steam-Kern-Programme: {0}.'; fr='Exécutables du cœur de Steam trouvés : {0}.'; es='Ejecutables del núcleo de Steam encontrados: {0}.'; it='Eseguibili del nucleo di Steam trovati: {0}.'; pt='Executáveis do núcleo do Steam encontrados: {0}.'; pl='Znaleziono pliki wykonywalne rdzenia Steam: {0}.'; zh='找到 Steam 核心可执行文件：{0}。' }
Add-Entry 'diagnostics.check.steamCore.notFound' @{ ru='Не удалось найти steam.exe / steamservice.exe в указанной папке.'; en="Couldn't find steam.exe / steamservice.exe in the specified folder."; de='steam.exe / steamservice.exe konnte im angegebenen Ordner nicht gefunden werden.'; fr='Impossible de trouver steam.exe / steamservice.exe dans le dossier indiqué.'; es='No se pudo encontrar steam.exe / steamservice.exe en la carpeta indicada.'; it='Impossibile trovare steam.exe / steamservice.exe nella cartella specificata.'; pt='Não foi possível encontrar steam.exe / steamservice.exe na pasta especificada.'; pl='Nie udało się znaleźć steam.exe / steamservice.exe w podanym folderze.'; zh='在指定文件夹中找不到 steam.exe / steamservice.exe。' }
Add-Entry 'diagnostics.check.steamCore.error' @{ ru='Ошибка сканирования папки Steam: {0}'; en='Error scanning the Steam folder: {0}'; de='Fehler beim Scannen des Steam-Ordners: {0}'; fr="Erreur lors de l'analyse du dossier Steam : {0}"; es='Error al escanear la carpeta de Steam: {0}'; it='Errore durante la scansione della cartella di Steam: {0}'; pt='Erro ao verificar a pasta do Steam: {0}'; pl='Błąd skanowania folderu Steam: {0}'; zh='扫描 Steam 文件夹时出错：{0}' }
Add-Entry 'diagnostics.check.folders.title' @{ ru='Папки'; en='Folders'; de='Ordner'; fr='Dossiers'; es='Carpetas'; it='Cartelle'; pt='Pastas'; pl='Foldery'; zh='文件夹' }
Add-Entry 'diagnostics.check.folders.none' @{ ru='Дополнительные папки не настроены.'; en='No additional folders configured.'; de='Keine zusätzlichen Ordner konfiguriert.'; fr='Aucun dossier supplémentaire configuré.'; es='No hay carpetas adicionales configuradas.'; it='Nessuna cartella aggiuntiva configurata.'; pt='Nenhuma pasta adicional configurada.'; pl='Nie skonfigurowano dodatkowych folderów.'; zh='未配置附加文件夹。' }
Add-Entry 'diagnostics.check.folders.allOk' @{ ru='Все дополнительные папки доступны ({0}).'; en='All additional folders are accessible ({0}).'; de='Alle zusätzlichen Ordner sind verfügbar ({0}).'; fr='Tous les dossiers supplémentaires sont accessibles ({0}).'; es='Todas las carpetas adicionales están disponibles ({0}).'; it='Tutte le cartelle aggiuntive sono accessibili ({0}).'; pt='Todas as pastas adicionais estão acessíveis ({0}).'; pl='Wszystkie dodatkowe foldery są dostępne ({0}).'; zh='所有附加文件夹均可访问 ({0})。' }
Add-Entry 'diagnostics.check.folders.someMissing' @{ ru='Не найдено {0} из {1} папок: {2}.'; en='{0} of {1} folders not found: {2}.'; de='{0} von {1} Ordnern nicht gefunden: {2}.'; fr='{0} dossier(s) sur {1} introuvable(s) : {2}.'; es='No se encontraron {0} de {1} carpetas: {2}.'; it='Non trovate {0} cartelle su {1}: {2}.'; pt='Não encontradas {0} de {1} pastas: {2}.'; pl='Nie znaleziono {0} z {1} folderów: {2}.'; zh='未找到 {1} 个文件夹中的 {0} 个：{2}。' }
Add-Entry 'diagnostics.check.executables.title' @{ ru='EXE-файлы'; en='Executable files'; de='Ausführbare Dateien'; fr='Fichiers exécutables'; es='Archivos ejecutables'; it='File eseguibili'; pt='Arquivos executáveis'; pl='Pliki wykonywalne'; zh='可执行文件' }
Add-Entry 'diagnostics.check.executables.none' @{ ru='Отдельные исполняемые файлы не настроены.'; en='No separate executables configured.'; de='Keine separaten ausführbaren Dateien konfiguriert.'; fr='Aucun exécutable séparé configuré.'; es='No hay ejecutables independientes configurados.'; it='Nessun eseguibile separato configurato.'; pt='Nenhum executável separado configurado.'; pl='Nie skonfigurowano oddzielnych plików wykonywalnych.'; zh='未配置单独的可执行文件。' }
Add-Entry 'diagnostics.check.executables.allOk' @{ ru='Все отслеживаемые файлы найдены ({0}).'; en='All tracked files were found ({0}).'; de='Alle überwachten Dateien wurden gefunden ({0}).'; fr='Tous les fichiers suivis ont été trouvés ({0}).'; es='Se encontraron todos los archivos rastreados ({0}).'; it='Tutti i file monitorati sono stati trovati ({0}).'; pt='Todos os arquivos monitorados foram encontrados ({0}).'; pl='Znaleziono wszystkie monitorowane pliki ({0}).'; zh='已找到所有受跟踪的文件 ({0})。' }
Add-Entry 'diagnostics.check.executables.someMissing' @{ ru='Не найдено {0} из {1} файлов: {2}.'; en='{0} of {1} files not found: {2}.'; de='{0} von {1} Dateien nicht gefunden: {2}.'; fr='{0} fichier(s) sur {1} introuvable(s) : {2}.'; es='No se encontraron {0} de {1} archivos: {2}.'; it='Non trovati {0} file su {1}: {2}.'; pt='Não encontrados {0} de {1} arquivos: {2}.'; pl='Nie znaleziono {0} z {1} plików: {2}.'; zh='未找到 {1} 个文件中的 {0} 个：{2}。' }
Add-Entry 'diagnostics.check.firewall.title' @{ ru='Брандмауэр'; en='Firewall'; de='Firewall'; fr='Pare-feu'; es='Firewall'; it='Firewall'; pt='Firewall'; pl='Zapora'; zh='防火墙' }
Add-Entry 'diagnostics.check.firewall.ok' @{ ru='Чтение правил Microsoft Defender Firewall работает (найдено правил Steamoff: {0}).'; en='Reading Microsoft Defender Firewall rules works (Steamoff rules found: {0}).'; de='Das Lesen der Microsoft Defender Firewall-Regeln funktioniert (gefundene Steamoff-Regeln: {0}).'; fr='La lecture des règles du pare-feu Microsoft Defender fonctionne (règles Steamoff trouvées : {0}).'; es='La lectura de reglas de Microsoft Defender Firewall funciona (reglas de Steamoff encontradas: {0}).'; it='La lettura delle regole di Microsoft Defender Firewall funziona (regole Steamoff trovate: {0}).'; pt='A leitura das regras do Microsoft Defender Firewall funciona (regras do Steamoff encontradas: {0}).'; pl='Odczyt reguł zapory Microsoft Defender działa (znalezione reguły Steamoff: {0}).'; zh='可以读取 Microsoft Defender 防火墙规则（找到 Steamoff 规则数：{0}）。' }
Add-Entry 'diagnostics.check.firewall.accessDenied' @{ ru='Нет доступа к Microsoft Defender Firewall — требуются права администратора.'; en='No access to Microsoft Defender Firewall — administrator rights are required.'; de='Kein Zugriff auf die Microsoft Defender Firewall — Administratorrechte erforderlich.'; fr='Aucun accès au pare-feu Microsoft Defender — des droits administrateur sont nécessaires.'; es='Sin acceso a Microsoft Defender Firewall: se requieren derechos de administrador.'; it='Nessun accesso a Microsoft Defender Firewall: sono necessari diritti di amministratore.'; pt='Sem acesso ao Microsoft Defender Firewall — são necessários direitos de administrador.'; pl='Brak dostępu do zapory Microsoft Defender — wymagane są uprawnienia administratora.'; zh='无法访问 Microsoft Defender 防火墙——需要管理员权限。' }
Add-Entry 'diagnostics.check.firewall.error' @{ ru='Не удалось прочитать правила firewall: {0}'; en="Couldn't read firewall rules: {0}"; de='Firewall-Regeln konnten nicht gelesen werden: {0}'; fr='Impossible de lire les règles du pare-feu : {0}'; es='No se pudieron leer las reglas del firewall: {0}'; it='Impossibile leggere le regole del firewall: {0}'; pt='Não foi possível ler as regras do firewall: {0}'; pl='Nie udało się odczytać reguł zapory: {0}'; zh='无法读取防火墙规则：{0}' }
Add-Entry 'diagnostics.check.autostart.title' @{ ru='Автозапуск'; en='Autostart'; de='Autostart'; fr='Démarrage automatique'; es='Inicio automático'; it='Avvio automatico'; pt='Inicialização automática'; pl='Autostart'; zh='自动启动' }
Add-Entry 'diagnostics.check.autostart.disabled' @{ ru='Автозапуск отключён в настройках — проверка пропущена.'; en='Autostart is disabled in Settings — check skipped.'; de='Autostart ist in den Einstellungen deaktiviert — Prüfung übersprungen.'; fr='Le démarrage automatique est désactivé dans les paramètres — vérification ignorée.'; es='El inicio automático está desactivado en los ajustes; se omitió la comprobación.'; it="L'avvio automatico è disabilitato nelle impostazioni — controllo saltato."; pt='A inicialização automática está desativada nas configurações — verificação ignorada.'; pl='Autostart jest wyłączony w ustawieniach — pominięto sprawdzenie.'; zh='设置中已禁用自动启动——已跳过检查。' }
Add-Entry 'diagnostics.check.autostart.installed' @{ ru='Задача автозапуска установлена в Планировщике заданий Windows.'; en='The autostart task is installed in Windows Task Scheduler.'; de='Die Autostart-Aufgabe ist in der Windows-Aufgabenplanung installiert.'; fr='La tâche de démarrage automatique est installée dans le Planificateur de tâches Windows.'; es='La tarea de inicio automático está instalada en el Programador de tareas de Windows.'; it="L'attività di avvio automatico è installata nell'Utilità di pianificazione di Windows."; pt='A tarefa de inicialização automática está instalada no Agendador de Tarefas do Windows.'; pl='Zadanie autostartu jest zainstalowane w Harmonogramie zadań systemu Windows.'; zh='自动启动任务已安装在 Windows 任务计划程序中。' }
Add-Entry 'diagnostics.check.autostart.missing' @{ ru='Автозапуск включён в настройках, но задача в Планировщике заданий не найдена. Сохраните настройки для её установки.'; en="Autostart is enabled in Settings, but the task wasn't found in Task Scheduler. Save Settings to install it."; de='Autostart ist in den Einstellungen aktiviert, aber die Aufgabe wurde in der Aufgabenplanung nicht gefunden. Speichern Sie die Einstellungen, um sie zu installieren.'; fr="Le démarrage automatique est activé dans les paramètres, mais la tâche est introuvable dans le Planificateur de tâches. Enregistrez les paramètres pour l'installer."; es='El inicio automático está activado en los ajustes, pero no se encontró la tarea en el Programador de tareas. Guarda los ajustes para instalarla.'; it="L'avvio automatico è abilitato nelle impostazioni, ma l'attività non è stata trovata nell'Utilità di pianificazione. Salva le impostazioni per installarla."; pt='A inicialização automática está ativada nas configurações, mas a tarefa não foi encontrada no Agendador de Tarefas. Salve as configurações para instalá-la.'; pl='Autostart jest włączony w ustawieniach, ale nie znaleziono zadania w Harmonogramie zadań. Zapisz ustawienia, aby je zainstalować.'; zh='设置中已启用自动启动，但在任务计划程序中未找到该任务。请保存设置以安装它。' }
Add-Entry 'diagnostics.check.autostart.error' @{ ru='Не удалось проверить задачу автозапуска: {0}'; en="Couldn't check the autostart task: {0}"; de='Die Autostart-Aufgabe konnte nicht geprüft werden: {0}'; fr='Impossible de vérifier la tâche de démarrage automatique : {0}'; es='No se pudo comprobar la tarea de inicio automático: {0}'; it="Impossibile verificare l'attività di avvio automatico: {0}"; pt='Não foi possível verificar a tarefa de inicialização automática: {0}'; pl='Nie udało się sprawdzić zadania autostartu: {0}'; zh='无法检查自动启动任务：{0}' }

# ---------- apply ----------
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

foreach ($lang in $languages) {
    $path = Join-Path $root "$lang.json"
    $text = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)

    # Locate the last closing brace.
    $lastBrace = $text.LastIndexOf('}')
    $head = $text.Substring(0, $lastBrace)
    $head = $head.TrimEnd("`r", "`n", " ")

    $added = 0
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append($head)

    foreach ($entry in $entries) {
        $key = $entry.Key
        if ($text.Contains("`"$key`":")) {
            continue
        }

        $value = $entry.Texts[$lang]
        if (-not $value) { $value = $entry.Texts['en'] }

        $escapedKey = $key.Replace('\', '\\').Replace('"', '\"')
        $escapedValue = $value.Replace('\', '\\').Replace('"', '\"')

        [void]$sb.Append(",`r`n  `"$escapedKey`": `"$escapedValue`"")
        $added++
    }

    [void]$sb.Append("`r`n}")
    [void]$sb.Append("`r`n")

    if ($added -gt 0) {
        [System.IO.File]::WriteAllText($path, $sb.ToString(), $utf8NoBom)
    }

    Write-Output "$lang.json -> added $added keys"
}
